<?php
class List_Controller extends MasterController {	/**	 * @var 模組資訊	 */	protected $module_metadata = array();	/**	 * @var 模組物件	 */	protected $module_objects = array();		/**	 * @var 清單欄位	 */	protected $list_fields = array();	public function main() {				// 取得模組代碼 並 取得模組元件		$module_code = $this -> module_io -> mod;		// 驗證模組是否存在		if (!isset($this -> master_config["modules"][$module_code])) {			$this -> module_showbox -> set_message("不存在的模組");			$this -> module_go -> back();		}				// 取得模組元資訊		$this -> module_metadata = $this -> master_config["modules"][$module_code];		// 如為設定模組(則直接導向編輯頁面)
		if ($this -> module_metadata["type"] == "Config") {			$this -> module_go -> page("fix.php?mod=" . $this -> module_io -> mod);		}				// 載入模組		$this -> load_modules();				$this -> load_fields();	}	/**	 * 載入指定類型的所有模組	 */	private function load_modules() {		// 載入指定類型的所有模組		$module_action = $this -> module_dao -> get_object("module");		$this -> module_objects = $module_action -> get_modules($this -> module_metadata["type"]);				foreach($this -> module_objects as $key => $module){			$module -> extend_field_value($module);			$this -> load_component($module, $this -> module_metadata["fields"]);			$this -> module_objects[$key] = $module;		}	}		/**	 * 載入操作元件	 * @param MDL_Module $module 模組	 * @param Array $fieldMetadatas 欄位資訊	 */	private function load_component(& $module, $fieldMetadatas) {		require_once ($this -> config_full_application_path . "/custom/components/Component.php");		foreach ($fieldMetadatas as $key => $fieldMetadata) {			require_once ($this -> config_full_application_path . "/custom/components/" . $fieldMetadata["type"] . "_Component.php");			$component_name = $fieldMetadata["type"] . "_Component";			$fieldMetadata["variable"] = $key;			$module -> {$fieldMetadata["variable"]} = new $component_name($module -> {$fieldMetadata["variable"]} , $fieldMetadata, $module);		}			}			private function load_fields(){		foreach($this -> module_metadata["fields"] as $key => $field){			if($field["list"] == "Y"){				$field["variable"] = $key;				$this -> list_fields[] = $field;			}		}	}	/**	 * 新增模組	 */	public function add_module() {
		$this -> module_go -> page("add.php?mod=" . $this -> module_io -> mod);
	}	/**	 * 刪除模組	 */	public function del_module() {
		if (!is_array($this -> module_io -> ids)) {
			return;
		}
		foreach ($this -> module_io -> ids as $id) {
			$module = $this -> module_dao -> get_object("module", $id);			if ($module -> is_exists()) {				$module -> delete();							}		}		$this -> module_showbox -> set_message("刪除成功!");
		$this -> module_go -> back();		
	}}?>