<!DOCTYPE html>
<html class="lockscreen">
    <head>
        <meta charset="UTF-8">
        <title>AdminLTE | Lockscreen</title>
        <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
        <link href="css/bootstrap.min.css" rel="stylesheet" type="text/css" />
        <link href="css/font-awesome.min.css" rel="stylesheet" type="text/css" />
        <!-- Theme style -->
        <link href="css/AdminLTE.css" rel="stylesheet" type="text/css" />

		<script src="<?php echo $this -> config_machine_relative_jquery_lib_path; ?>/jquery.2.1.1.min.js"></script>

        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
          <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
        <![endif]-->
    </head>
    <body>
        <!-- Automatic element centering using js -->
        <div class="center">
            <div class="headline text-center" id="time">
            	<?php echo $this -> check_date_time; ?>
                <!-- Time auto generated by js -->
            </div><!-- /.headline -->
            
            <!-- User name -->
            <div class="lockscreen-name" style="font-size:30px;">
            	(本介面即將修改)
            	<br />
            	<?php echo $this -> work_status; ?>
            	<br />
            	<?php echo $this -> member -> title -> get_value(); ?>
            	<br />
            	<?php if($this -> work_setting["default_value"] == "Y"): ?>
            	<div style="text-align:left;font-size:13px;margin:0 auto;width:500px;">
            		<br />
            		由於您的部門上班時段尚未設定，因此本次採用預設值：<br />
            		08:00 上班<br />
            		12:00 開始休息<br />
            		13:00 結束休息<br />
            		17:00 下班<br />
            		<br />
            		<span style="color:red;">未來介面修正後，畫面會先告知本資訊，再由您自行點選打卡按鈕進行打卡。</span>
            	</div>
            	<?php endif; ?>
            </div>
            
            

                     
        </div><!-- /.center -->

        
        <script src="js/bootstrap.min.js" type="text/javascript"></script>

        <!-- page script -->
        <script type="text/javascript">
            $(function() {
               // startTime();
                $(".center").center();
                $(window).resize(function() {
                    $(".center").center();
                });
            });

            /*  */
            function startTime()
            {
                var today = new Date();
                var h = today.getHours();
                var m = today.getMinutes();
                var s = today.getSeconds();

                // add a zero in front of numbers<10
                m = checkTime(m);
                s = checkTime(s);

                //Check for PM and AM
                var day_or_night = (h > 11) ? "PM" : "AM";

                //Convert to 12 hours system
                if (h > 12)
                    h -= 12;

                //Add time to the headline and update every 500 milliseconds
                $('#time').html(h + ":" + m + ":" + s + " " + day_or_night);
                setTimeout(function() {
                    startTime()
                }, 500);
            }

            function checkTime(i)
            {
                if (i < 10)
                {
                    i = "0" + i;
                }
                return i;
            }

            /* CENTER ELEMENTS IN THE SCREEN */
            jQuery.fn.center = function() {
                this.css("position", "absolute");
                this.css("top", Math.max(0, (($(window).height() - $(this).outerHeight()) / 2) +
                        $(window).scrollTop()) - 30 + "px");
                this.css("left", Math.max(0, (($(window).width() - $(this).outerWidth()) / 2) +
                        $(window).scrollLeft()) + "px");
                return this;
            }
        </script>
        <?php if($this -> is_overtime): ?>
		<link rel='stylesheet' href='<?php echo $this -> config_machine_relative_jquery_lib_path; ?>/sweetalert/sweetalert.css' type='text/css' />
		<script src='<?php echo $this -> config_machine_relative_jquery_lib_path; ?>/sweetalert/sweetalert-dev.js'></script>
		<script>
			$(document).ready(function(){
				swal({
					showCancelButton: true,
					title: "您打卡的時間並非在上班時間\r\n是否申請加班？",
					text: "如放棄，系統將自動將您打卡時間調整為正常下班時間\r\n如申請加班，請填寫加班申請表",
					confirmButtonText: "我要申請加班",
					cancelButtonText: "我要放棄",
					closeOnConfirm: false,
  					closeOnCancel: false
				},
				function(isConfirm){
					if (isConfirm) {
						location.href='add_item.php?mod=overtime';
					} else {
						
						$.post( "api.php", { "abort_work_plus": "1", "type":"<?php echo $this -> overtimes[0]["type"]; ?>","item_id": "<?php echo $this -> last_item_id; ?>" })
						  .done(function( data ) {
						  	if(data == "success"){
						    	swal("成功放棄", "系統已自動將您打卡時間調整為正常下班時間", "error");
						   	}
						});
						
						// swal("成功放棄", "系統已自動將您打卡時間調整為正常下班時間", "error");
					}
				});
			});
		</script>
        <?php endif; ?>
    </body>
</html>